DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS artpiece;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  wallet TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE artpiece (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  artist_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  art NVARCHAR(100) NOT NULL,
  FOREIGN KEY (artist_id) REFERENCES user (id)
);